export const AGREEMENT_V3_ABI = [
    "constructor((string protocolName, (string name, string contact)[] contactDetails, (string assetRecoveryAddress, (string accountAddress, uint8 childContractScope)[] accounts, string caip2ChainId)[] chains, (uint256 bountyPercentage, uint256 bountyCapUSD, bool retainable, uint8 identity, string diligenceRequirements, uint256 aggregateBountyCapUSD) bountyTerms, string agreementURI) _details, address _chainValidator, address _initialOwner)",
    "error Agreement__AccountNotFoundByAddress(string caip2ChainId, string accountAddress)",
    "error Agreement__AggregateBountyCapLessThanBountyCap(uint256 aggregateBountyCapUSD, uint256 bountyCapUSD)",
    "error Agreement__BountyPercentageExceedsMaximum(uint256 bountyPercentage, uint256 maxPercentage)",
    "error Agreement__CannotRemoveAllAccounts(string caip2ChainId)",
    "error Agreement__CannotSetBothAggregateBountyCapUsdAndRetainable()",
    "error Agreement__ChainIdHasZeroLength()",
    "error Agreement__ChainNotFoundByCaip2Id(string caip2ChainId)",
    "error Agreement__DuplicateChainId(string caip2ChainId)",
    "error Agreement__InvalidAccountAddress(string caip2ChainId, uint256 accountIndex)",
    "error Agreement__InvalidAssetRecoveryAddress(string caip2ChainId)",
    "error Agreement__InvalidChainId(string caip2ChainId)",
    "error Agreement__InvalidContactDetails(uint256 contactIndex)",
    "error Agreement__ZeroAccountsForChainId(string caip2ChainId)",
    "error Agreement__ZeroAddress()",
    "error OwnableInvalidOwner(address owner)",
    "error OwnableUnauthorizedAccount(address account)",
    "event AccountAdded(string caip2ChainId, (string accountAddress, uint8 childContractScope) account)",
    "event AccountRemoved(string caip2ChainId, string accountAddress)",
    "event BountyTermsSet((uint256 bountyPercentage, uint256 bountyCapUSD, bool retainable, uint8 identity, string diligenceRequirements, uint256 aggregateBountyCapUSD) newBountyTerms)",
    "event ChainAdded(string caip2ChainId, string assetRecoveryAddress, (string accountAddress, uint8 childContractScope)[] accounts)",
    "event ChainRemoved(string caip2ChainId)",
    "event ChainSet(string caip2ChainId, string assetRecoveryAddress, (string accountAddress, uint8 childContractScope)[] accounts)",
    "event ContactDetailsSet((string name, string contact)[] newContactDetails)",
    "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
    "event ProtocolNameSet(string newName)",
    "function MAX_BOUNTY_PERCENTAGE() view returns (uint256)",
    "function addAccounts(string _caip2ChainId, (string accountAddress, uint8 childContractScope)[] _accounts)",
    "function addChains((string assetRecoveryAddress, (string accountAddress, uint8 childContractScope)[] accounts, string caip2ChainId)[] _chains)",
    "function addOrSetChains((string assetRecoveryAddress, (string accountAddress, uint8 childContractScope)[] accounts, string caip2ChainId)[] _chains)",
    "function getAgreementURI() view returns (string)",
    "function getBountyTerms() view returns ((uint256 bountyPercentage, uint256 bountyCapUSD, bool retainable, uint8 identity, string diligenceRequirements, uint256 aggregateBountyCapUSD))",
    "function getChainIds() view returns (string[])",
    "function getChainValidator() view returns (address)",
    "function getDetails() view returns ((string protocolName, (string name, string contact)[] contactDetails, (string assetRecoveryAddress, (string accountAddress, uint8 childContractScope)[] accounts, string caip2ChainId)[] chains, (uint256 bountyPercentage, uint256 bountyCapUSD, bool retainable, uint8 identity, string diligenceRequirements, uint256 aggregateBountyCapUSD) bountyTerms, string agreementURI) _details)",
    "function getProtocolName() view returns (string)",
    "function owner() view returns (address)",
    "function removeAccounts(string _caip2ChainId, string[] _accountAddresses)",
    "function removeChains(string[] _caip2ChainIds)",
    "function renounceOwnership()",
    "function setBountyTerms((uint256 bountyPercentage, uint256 bountyCapUSD, bool retainable, uint8 identity, string diligenceRequirements, uint256 aggregateBountyCapUSD) _bountyTerms)",
    "function setChains((string assetRecoveryAddress, (string accountAddress, uint8 childContractScope)[] accounts, string caip2ChainId)[] _chains)",
    "function setContactDetails((string name, string contact)[] _contactDetails)",
    "function setProtocolName(string _protocolName)",
    "function transferOwnership(address newOwner)",
];

export const CHAINLOG_ABI = [
    "function getAddress(bytes32) view returns (address)",
];
