name: Setup Foundry

on:
  push:
    paths:
      - "scripts/setup-foundry.py"
      - "scripts/setup-foundry/**"
  pull_request:
    paths:
      - "scripts/setup-foundry.py"
      - "scripts/setup-foundry/**"

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Setup Foundry
        run: make test-setup-foundry
