name: Tests

on: [push, pull_request]

permissions:
  contents: read
  attestations: read

env:
  FOUNDRY_RELEASE: v1.7.1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add Foundry to PATH
        run: echo "${HOME}/.foundry/bin" >> "${GITHUB_PATH}"

      - name: Install Foundry
        run: make install-foundry release="$FOUNDRY_RELEASE"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Verify Foundry
        run: make verify-foundry release="$FOUNDRY_RELEASE"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Run Forge tests
        run: |
          make test
        id: test
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
          AVAX_RPC_URL: ${{ secrets.AVAX_RPC_URL }}
