name: Tests

on: [push, pull_request]

jobs:
  setup-foundry:
    name: Setup Foundry CLI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Setup Foundry CLI
        run: make test-setup-foundry

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge tests
        run: |
          make test
        id: test
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
          AVAX_RPC_URL: ${{ secrets.AVAX_RPC_URL }}
